# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  # GetX for Statemanagement
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  # for API call
  http: ^1.0.0
  # CSV to List
  csv: ^6.0.0
  # Lottie Animation
  lottie: ^3.0.0
  # For Storing Data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  # Change package name  
  # change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/